### ISSUE TITLE
MarkDown Style 변경 방법 문의

### ISSUE THREAD

**Issue by nasa1515** [zoomKoding/zoomkoding-gatsby-blog#15]
이전에 보내드린 메일과 같이 계속해서 여러가지 기능 테스트 해보고 있습니다.~ 

 
![image](https://user-images.githubusercontent.com/69498804/126242508-2b24416a-4191-4a40-a972-b5bb3a35c2ae.png)

현재 다음과 같이 MD 파일로 여러가지 가이드 작성 중에 IMAGE의 Position에 대한 값을 어느 파일에서 바꿔야 할지 여쭙고 싶습니다.

(원하는 모습은 Image에 대한 무조건 적인 가운데 정렬이 아닌 Left 정렬을 원합니다.) 
 
![image](https://user-images.githubusercontent.com/69498804/126242565-32678644-1302-46bf-805a-3eaa453339da.png)

현재는 다음과 같이  position: relative로 잡힌 파일에서 수정 테스트는 해봤는데 원하는 기능이 구현이 안되네욥.

**Comment by zoomKoding** [comment]
마크다운으로 추가된 이미지 전체를 좌측 정렬하시려면 1045번째 줄을 주석처리하시면 됩니다!


```css
.markdown .gatsby-resp-image-wrapper {
  display: flex !important;
  // justify-content: center !important; // 이 줄을 주석 처리하시면 됩니다!
  width: 100% !important;
  max-height: $content-image-max-height !important;
