### ISSUE TITLE
Font 변경 및 md image 정렬

### ISSUE THREAD

**Issue by nasa1515** [zoomKoding/zoomkoding-gatsby-blog#17]
줌코딩님!! 질문 두개 드립니다!!

1. MD Image 정렬 기능 제한. (해당 코드 변경해도 Left 정렬 되지 않음.)
![image](https://user-images.githubusercontent.com/69498804/126468900-7095d521-0938-4840-a482-74a259adb125.png)

2. css 기본 폰트 이외의 Google Font 사용법

**Comment by zoomKoding** [comment]
원석님 안녕하세요!
정렬 문제를 해결해서 원석님 블로그 레포에 Pull Request 남겨놨습니다! :)
구글 폰트 같은 경우에는 [이 글](https://woojeongmin.com/2021/gatsby-blog/2-google-webfonts/) 참고하시면 좋을 것 같습니다!
