### ISSUE TITLE
Draft 기능

### ISSUE THREAD

**Issue by superbderrick** [zoomKoding/zoomkoding-gatsby-blog#19]
@zoomKoding 님, 안녕하세요! 질문 있습니다. 
혹시 블로그 Postting 관련해서 포스팅을 잠시 Draft 처리 할 수 있는 방법이 있을까요?

**Comment by zoomKoding** [comment]
현재 따로 기능을 지원하고 있지는 않습니다!

**Comment by superbderrick** [comment]
아 ! 일반 블로그들 처럼 , 비공개로 글을쓰거나 Draft로 여러 글을 쓰고 한번에 Publishing을 하는경우가 있어서, 말씀드렸었어요. 말씀해주신대로, 롴컬에서 작업하다, 한번에 Push해서 업데이트해야겠습니다 답변 감사해요:) 
![21F7EF2A-A2A9-4549-BE25-D132649E26BE](https://user-images.githubusercontent.com/7856611/126994964-532ae221-aa0b-40fa-a0cc-ebbe30e7d8d9.png)

**Comment by zoomKoding** [comment]
있으면 좋을 법한 기능이네요!
혹시 다른 분들도 이런 draft 기능이 필요하시면 다시 오픈하도록 하도록 하겠습니다 :)
