### ISSUE TITLE
rss.xml or sitemap 설정 관련.

### ISSUE THREAD

**Issue by nasa1515** [zoomKoding/zoomkoding-gatsby-blog#21]
안녕하세요 줌코딩님 많은 도움으로 인해 성공적으로 블로그 리빌딩 중입니다!! 

다름이 아니라 줌코딩님 Gastby 테마는 advanced-sitemap 플러그인을 사용 중이신 것 같은데 RSS는 따로 등록하지 않으신 상태이신가요

**Comment by zoomKoding** [comment]
@nasa1515님 안녕하세요!
RSS 설정은 따로 추가해두지 않았어서 추가 구현해서 푸쉬해두었습니다!
내용이 궁금하시다면 aa5b201 을 참고하시면 될 것 같습니다!
