### ISSUE TITLE
npm package error

### ISSUE THREAD

**Issue by C-Designer** [zoomKoding/zoomkoding-gatsby-blog#23]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: zoomkoding.com@1.1.0
npm ERR! Found: gatsby@2.32.13
npm ERR! node_modules/gatsby
npm ERR!   gatsby@"^2.32.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer gatsby@"^3.0.0-next.0" from gatsby-remark-copy-linked-files@3.2.0
npm ERR! node_modules/gatsby-remark-copy-linked-files
npm ERR!   gatsby-remark-copy-linked-files@"^3.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/c-design/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/c-design/.npm/_logs/2021-08-10T12_47_45_877Z-debug.log

**Comment by zoomKoding** [comment]
@C-Designer님 안녕하세요!
이 버그가 지금 C-Designer님 블로그 레파지토리 master 브랜치에서 npm install 했을때 나오는 버그 인가요?
방금 레파지토리 클론받아서 npm install 진행해봤는데 이상없이 잘 되네요!
