### ISSUE TITLE
사소한 버그?가 있는 것 같아 Issues 남깁니다.

### ISSUE THREAD

**Issue by nasa1515** [zoomKoding/zoomkoding-gatsby-blog#25]
![image](https://user-images.githubusercontent.com/69498804/129159312-1030dcfe-da99-4c4c-86e5-796d0221a728.png)

위 그림과 같이 다음 글, 이전 글 위치가 약간 이상하네요... 

Post Page에서 위에 위치한 글이 다음 글.  아래에 위치한 글이 이전 글이 되어야 할 것 같아서

![image](https://user-images.githubusercontent.com/69498804/129167707-706e25fd-8329-48f6-b2cd-809b0d556842.png)

nextPost와 prevPost 위치만 바꿔서 해결했습니다!

PS:// 

추가적으로 질문하고 싶은 부분이 있습니다.!!

![image](https://user-images.githubusercontent.com/69498804/129286976-8ca18d78-654c-42c5-bed1-9e472e0c43a5.png)

위 글 처럼 포스트를 작성하고 있는 도중에 ```md```로 묶은 박스와 일단 markdown 의 글꼴과 font-size가 다른 것 같은데

혹시 ```md``` 박스의 font나 size 설정은 어디서 해야 할까요

**Comment by zoomKoding** [comment]
@nasa1515 님 안녕하세요! 좋은 제안 감사합니다:)
현재 코드 블록의 스타일링은  prismjs의 `prism-tomorrow` library를 사용하는 중입니다!
코드 블록 내부 md에 대한 스타일링은 _markdown-style.scss 파일에서 아래와 같이 진행하시면 됩니다.
```css
.markdown pre code.language-md {
  font-size: 14px;
  color: red;
}
```
