### ISSUE TITLE
Dark Mode 최적화 문의...

### ISSUE THREAD

**Issue by nasa1515** [zoomKoding/zoomkoding-gatsby-blog#27]
줌코딩님 안녕하세요!! 매번 빠르게 이슈 답변 주셔서 감사합니다!1

이번에는 Dark Mode에서 표 구성 시 font color가 이상하게 나오는 상황을 발견했습니다.

![image](https://user-images.githubusercontent.com/69498804/129865268-17d46d53-8e27-4a09-9a5a-94c0c116a5d6.png)

확인해보니 해당 본문 폰트, 표 Font color가 
![image](https://user-images.githubusercontent.com/69498804/129865318-e8687977-2438-4fde-b2fe-cea0a208bfcf.png)

--primary-text-color로 같이 묶여있어서 그런 것 같은데 혹시 어떻게 해결 하셨나요?

**Comment by zoomKoding** [comment]
@nasa1515 님 안녕하세요!
답이 늦어서 죄송합니다!🙏
말씀해주신대로 테이블에 문제가 좀 있네요. 수정해서 배포하였습니다!
원석님 블로그에 적용하고 싶으시다면 185f35b 를 참고하셔서 해결하시면 될 것 같습니다!
항상 적극적으로 이슈 남겨주시고 의견 주셔서 감사합니다! 👍

**Comment by nasa1515** [comment]
아닙니다!!
매번 빠르게 답변 남겨주시고 적극적으로 해결해주셔서 
저야말로 감사드립니다.!! 👏
