### ISSUE TITLE
google adsense 기능 추가 요청

### ISSUE THREAD

**Issue by nasa1515** [zoomKoding/zoomkoding-gatsby-blog#32]
안녕하세요 줌코딩님!! 이슈 탭에 요청 드린 기능들 다 반영해 주셔서 블로그 테마 잘 사용하고 있습니다.
다름이 아니라 이번에는 Google adsense 승인을 받았을 경우에 블로그 하단에 광고를 삽입하는 기능에 대해서도 업데이트가 가능하실 지 여쭙고 싶습니다

**Comment by zoomKoding** [comment]
@nasa1515 님 안녕하세요!
항상 좋은 제안 감사드립니다!
애드센스 기능 관련해서 검토해보고 말씀드리도록 하겠습니다!🙏

**Comment by zoomKoding** [comment]
@nasa1515 님 안녕하세요! 답장이 늦어서 죄송합니다!😭

확인해보니 광고를 넣고 싶으신 지점이 다양하기 떄문에 애드센스의 경우 제가 빌트인으로 기능을 제공하기 보다 직접 코드를 삽입하시는 것이 나을 듯하네요!

예를 들어 블로그 포스팅의 상단과 끝부분에 광고를 추가하고 싶으시다면 `src/templates/blog-template.js`의 다음 지점에 광고를 넣으시면 될 것으로 보입니다👍

```js
...
return (
    <ThemeToggler>
      {({ theme }) => (
        <Layout>
          <SEO title={curPost?.title} description={curPost?.excerpt} />
          <PostHeader post={curPost} viewCount={viewCount} />
          {/* 글 헤더 밑에 광고를 넣고 싶다면 여기에 광고를 넣으세요 */}
          <PostContent html={curPost.html} />
          {/* 내용이 다 끝난 후에 광고를 넣고 싶다면 여기에 광고를 넣으세요 */}
          <PostCardsAdjacent prevPost={prevPost} nextPost={nextPost} />
          {utterancesRepo && <Utterances repo={utterancesRepo} theme={theme} />}
        </Layout>
      )}
    </ThemeToggler>
  );
```
