### ISSUE TITLE
gatsby-github-blog/

### ISSUE THREAD

**Issue by eunhye43** [zoomKoding/zoomkoding-gatsby-blog#33]
안녕하세요, 줌코딩님, 예쁜 블로그 만들어주셔서 감사합니다.
알려주신대로 구현해보려고 이것저것 만져보았는데, 깃헙 블로그는 처음이라 어디서 에러가 나는지 모르겠어서 글을 남깁니다.

* VSCODE와 terminal을 함께 사용하고 있는데, git add. -> git comit -m "..." -> npm run deploy 로 진행을 하면, 
[<img width="707" alt="image" src="https://user-images.githubusercontent.com/80014658/133430896-fdf62566-fb67-49fe-87cd-74a98c2c9396.png">](url)
수정사항을 다 변경하고, 저장해서 진행하면 이렇게 published가 나오고 완료가 되는데, https://eunhye43.github.io/majaeh412.github.io/ 제 깃헙 블로그에는 반영되지 않더라구요. local에서는 반영이 되는데 실제 제가 만든 깃헙블로그에는 반영되지 않아 어느 부분이 문제인지 모르겠습니다. vscode 함께 사용하고 있구요! 노드 버전도 14이상입니다! 브랜치도  Branch를 master(main)에서 gh-pages로 변경했구요!

혹시 제가 놓친 곳이 있다면 알려주시면 감사하겠습니다!

**Comment by zoomKoding** [comment]
@eunhye43 님 안녕하세요!
최근에 일이 좀 바뻐 이제 답을 드립니다!🙏
먼저 블로그 쓰려고 해주셔서 감사합니다ㅎㅎ
먼저 하나 궁금한 부분이 있는데 https://eunhye43.github.io 대신 https://eunhye43.github.io/majaeh412.github.io를 사용하시는 이유가 있으신가요? (개인적으로는 기본 깃헙페이지 home을 블로그로 쓰시는 것을 추천드립니다!😀)

지금과 같이 home이 아닌 주소로 배포를 진행하시려면 package.json에 아래를 추가하시고 진행하시면 될 것 같습니다!
진행해보시고 어떻게 됐는지 알려주시면 다시 도움 드리도록 하겠습니다!

```
"homepage": "https://eunhye43.github.io/majaeh412.github.io"
```

**Comment by eunhye43** [comment]
안녕하세요! 바쁘신데 시간내주셔서 정말 감사합니다 :>
말씀하신대로 home주소로 다시 만들어서 진행했는데도 여전히 적용이 안되더라구요!

git add.
git commit -m “..”
npm run deploy

터미널에서 적용한 명령어가 틀린걸까요?
vscode에서 모두 저장한 뒤 터미널에서 진행했습니다!

혹시 몰라 캡처본들을 첨부합니다. 확인부탁드립니다!
즐거운 추석 보내시고 시간나실 때 천천히 답장 부탁드려요 !

감사합니다!

**Comment by zoomKoding** [comment]
@eunhye43님 안녕하세요!
확인해보니 메타 정보를 수정하신 부분은 반영된 것으로 보이는데 이 부분이 맞나요?
이슈가 있는 부분을 좀 더 명확하게 말씀해주시면 확인해보겠습니다!
(위에 있는 댓글에 캠쳐본이 없네요😭)

![image](https://user-images.githubusercontent.com/36878344/134341666-21f58a5e-924b-4edb-9798-d38e7b94f788.png)

**Comment by zoomKoding** [comment]
@eunhye43 님 답변이 없으셔서 일단 닫아놓도록하겠습니다!
다른 이슈가 있으시면 이 이슈를 다시 여시거나 다른 이슈로 남겨주세요!🙏
