### ISSUE TITLE
Mathjax 수식 적용

### ISSUE THREAD

**Issue by yjksw** [zoomKoding/zoomkoding-gatsby-blog#34]
안녕하세요 ~~!! 
만들어주신 테마 너무 예쁘게 잘 쓰고 있습니다 ㅎㅎㅎ

다름이 아니라 이번에 수식을 적용하고자 $..$ , $$..$$ 을 사용했었는데요, 블로그 글에 적용이 안되어서 혹시 수식을 사용하는데 추가로 할 일이 필요한지 궁금하여 이슈 올립니다 !!

감사합니다 😊

**Comment by zoomKoding** [comment]
@yjksw님, 안녕하세요! 
이슈 알려주셔서 감사합니다!😂

확인해보니 사용하고 있는 mathjax 관련 library에 문제가 있어서 library를 변경하여 이슈를 해소했습니다!
변경된 내용을 @yjksw님 블로그에 반영하고 싶으시다면 [이글](https://www.zoomkoding.com/how-to-update-gatsby-blog/)을 참고하시면 좋을 것 같습니다!
진행해보시고 여전히 이슈가 있으시다면 다시 이슈 남겨주세요!🙏

**Comment by zoomkoding** [comment]
@yjksw님 안녕하세요!
다름이 아니라 mathjax 관련해서 알려드릴 부분이 있어서 댓글 남깁니다.
기존에 지원하던 mathjax 관련해서 이슈를 가지고 계신 분들이 여럿 계셔서, 
**이번 이후 버전에서는 mathjax 지원을 당분간 중지해야할 것 같습니다.**

혹시나 지금 이후 버전을 pull 받으시면 mathjax 기능을 사용하지 못하게 될 수도 있으니,
당분간은 테마 업데이트 내용을 풀 받지 않으실 것을 추천 드립니다.

최대한 빠른 시일 내에 이슈 해소해서 답변 드리도록 하겠습니다!🙏

**Comment by yjksw** [comment]
엇 !! 친절하게 알려주셔서 정말 감사합니다 ~~! 😊
제 블로그 보고 같이 개발하는 친구들이 너무 예쁘고 가독성이 좋다고 말해줬어요 ㅎㅎㅎ 예쁜 테마 넘 감사합니다 !!
