### ISSUE TITLE
Dummy Contents 삭제 관련 문의

### ISSUE THREAD

**Issue by sw-programmer** [zoomKoding/zoomkoding-gatsby-blog#35]
안녕하세요! 블로그 템플릿 너무 잘 이용 중인 1인입니다 :)

다름이 아니라 Contents 속 blog 카테고리에 속하는 글들을 없애고자 하는데, 없애면 다음과 같은 에러가 발생합니다.
----------------------------------------------
 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "emoji" on type "MarkdownRemarkFrontmatter".

If you don't expect "emoji" to exist on the type "MarkdownRemarkFrontmatter" it is most likely a typo.
However, if you expect "emoji" to exist there are a couple of solutions to common problems:
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and  
what shape they have
- You want to optionally use your field "emoji" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL      
schema. A quick fix is to add at least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content".  
Visit our docs to learn how you can define the schema for "MarkdownRemarkFrontmatter":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: src\templates\blog-template.js:92:9

---------------------------------------------------

이후 복원을 해도
ENOENT: no such file or directory, open 'C:\Users\~~\public\page-data\posts\블로그\page-data.json'

라는 오류가 발생합니다. 어찌저찌 복구하여 잘 사용하고 있으나, 이 경우 어떻게 대처해야 할까요?? :-)

감사합니다! :)

**Comment by zoomKoding** [comment]
안녕하세요, @sw-programmer님!
추석이라 답이 늦었습니다! 😭
@sw-programmer님의 블로그를 방문해보니 블로그 글들에 emoji field를 포함하지 않는 것으로 보입니다!
기본으로 들어있는 글들을 삭제하시고 작성하신 글의 meta data에 emoji를 포함하시면 해결 될 것으로 예상됩니다.
포스팅 마다 포함되어야하는 메타 데이터의 형태는 [여기](https://www.zoomkoding.com/gatsby-starter-zoomkoding-introduction/#-%EB%A9%94%ED%83%80-%EC%A0%95%EB%B3%B4)를 참고해주세요!
수정해서 배포해보시고 다른 이슈 있으시면 연락주세요!😊
