### ISSUE TITLE
코드 블럭 깨짐 버그 및 캐싱 이슈 

### ISSUE THREAD

**Issue by yjksw** [zoomKoding/zoomkoding-gatsby-blog#37]
안녕하세요 ~~!!! 
테마 여전히 잘 쓰고 있습니다 !! 👍 덕분에 블로그에 글 쓰는 맛이 나는 것 같아요 ~! 

다름이 아니라 블로그 글 중 코드블럭이 깨지는 현상이 발견이 되어서 제보하려고 합니다.
다음 [글](https://yjksw.github.io/oauth/) 에 아래와 같은 코드 블럭 깨짐 현상이 발생합니다. 
<img width="1334" alt="스크린샷 2021-09-25 오후 4 24 58" src="https://user-images.githubusercontent.com/63405904/134762888-9f7a8cc8-cbcb-49ca-b709-5ee1d6440c0b.png">
 

더불이 이전에 캐싱된 페이지로 인하여 이슈를 남겼었는데요,, !! 
그 이후에도 계속 그런 현상이 발견되어서 매번 새로 배포를 할 때마다 public 폴더와 .cache 폴더를 삭제해야하는 것이 맞을까요 ??

감사합니다 ~!! 😊🙌

**Comment by zoomKoding** [comment]
@yjksw님 안녕하세요!
확인해보니 코드 블록 쪽에 버그가 있네요! 수정해서 푸쉬해놨습니다!
다른 분들도 같은 이슈를 겪으셨을 것 같은데 리포트 해주셔서 감사합니다🙏

그리고 캐쉬 같은 경우에는 삭제하지 않으셔도 문제가 없어야하는 것이 맞습니다!
배포가 완료된 후에 브라우저가 이전 사이트 정보를 캐싱 해놓고 있기 때문에 바로 업데이트가 반영되지 않을 때가 있지 않을까 하는 생각이 드네요.

하지만 의심스러우시다면 packages.json에서 deploy 명령을 다음과 같이 수정하시면 더 확실할 것 같습니다🙏
`gatsby clean은 public, .cache 디렉토리를 삭제해주는 명령어입니다!`

```js
// package.json
{
    "scripts": {
        // ...
        "deploy": "gatsby clean && gatsby build && gh-pages -d public",
        // ...
    }
// ...
}
```
