### ISSUE TITLE
Upstream Pull 후 신규 Npm Build 시 이슈 발생...

### ISSUE THREAD

**Issue by nasa1515** [zoomkoding/zoomkoding-gatsby-blog#43]
안녕하세요 줌코딩님 오랜만에 질문 남깁니다.!!
근 2달정도만에 줌코딩님이 새롭게 커밋하셨던 내용들 Upstream으로 Pull 받아서 Commit 하려 했으나 
아래와 같은 이슈가 발생하는데 혹시 어느 부분에서 발생하는 건지 아실까요...?

![image](https://user-images.githubusercontent.com/69498804/138795648-a044222c-d99c-4197-be16-dbea9a1ebcd3.png)

**Comment by zoomkoding** [comment]
원석님 안녕하세요!
일단 저도 원석님 블로그 클론 받아 여러가지 시도를 해봤는데 원인을 파악하기가 쉽지 않네요😭
원석님 블로그 같은 경우에는 기본 테마에서 메타상으로 변경할 수 있는 것들 외에 코드를 변경하신 부분들이 있다보니,
제가 새로운 기능을 추가하고 업데이트 내용을 충돌없이 머지하기에는 어려움이 있어보입니다. 
(이 부분까지 완벽하게 할 수 있는 방법은 저도 조금 더 찾아보도록 하겠습니다🙏)

제안드리는 방법으로는 pull 받기 이전의 상태로 블로그를 운영하시고,
버그 수정이 필요하신 부분들이 있다면 따로 말씀해주시면 추가적인 지원을 드리도록 하겠습니다.

원석님 다시한번 항상 블로그를 잘 사용해주시고 문제도 공유해주셔서 너무 감사합니다!
깔끔한 해결책을 못드려 죄송합니다!🙏

**Comment by nasa1515** [comment]
아닙니다!! 항상 이렇게 빠른 지원해주셔서 저야 말로 감사드립니다!!!
