### ISSUE TITLE
cache busting 관련해서 질문드려요 ! 

### ISSUE THREAD

**Issue by eungwang1** [zoomkoding/zoomkoding-gatsby-blog#53]
안녕하세요 ! 올려주신 템플릿 너무 이뻐서 잘 쓰고 있습니다.

게시물을 올리고, deploy 했을 때, 

홈페이지 캐시를 삭제하지 않으면 반영이 안되더라구요 ㅠㅠ..

이것을 해결하는 방법이 cachebusting이라고 하는데.. 혹시 어떻게 적용해야 하는지 알 수 있을까요.. ?

**Comment by zoomkoding** [comment]
@eungwang1님 안녕하세요! 
말씀해주신 이슈가 어떻게 재현되는지 알 수 있을까요? 
브라우저에 캐쉬되서 발생하는 이슈인지 개츠비 서버에서 캐쉬된 정보를 업데이트 하지 않는 부분인지 조금더 확인을 해봐야할 것 같습니다!🙏
