### ISSUE TITLE
블로그 사용 관련 질문 2가지

### ISSUE THREAD

**Issue by Shim8934** [zoomkoding/zoomkoding-gatsby-blog#54]
안녕하세요, 제작해 주신 블로그 테마 잘 사용하고 있습니다! 매우 감사드려요.
다름이 아니라 2가지 궁금한 사항이 있어 질문 드릴게 있습니다.
제가 노드에 대해서 잘 모르는 부분이 있어 초심자 입장에서 질문한다 생각해 주시면 감사하겠습니다..!

1. 모바일로 블로그 Main 페이지에선 비율이 화면에 맞게 잘 나옵니다.
다만, Main 하단의 MORE를 누르거나, 다른 카테고리로 누르면 화면 너비가 최대치를 넘어가는 증상이 있던데 혹시 이 증상에 대해서 아시는 바가 있으실까요?

2. Google Search Console에 Sitemap.xml 등록과 관련된 질문입니다. 나름대로 소스를 파악한 바로는 gatsby 모듈 중에 sitemap.xml, sitemap-pages.xml을 제작해 주는 모듈이 있고, 그를 통해 생성하는 것으로 파악했습니다.
 문제는 Google Search Console에 해당 xml 들을 등록해 주고 나서 "가져올 수 없음" 인 상태로 계속 있는 것입니다. 다른 댓글들을 보다가 진혁님께서도 Search Console 정보를 등록해 두신 것을 봤는데 혹시 해당 sitemap.xml 정보를 가져오는데 며칠 걸리셨는지 여부를 알 수 있을까요?

![image](https://user-images.githubusercontent.com/58042201/150945281-a148a893-79bd-4075-bca3-a0ea406752fc.png)

**Comment by zoomkoding** [comment]
@Shim8934님 안녕하세요~! 궁금한 부분들 잘 정리해서 올려주셔서 감사합니다.
1번째 이슈는 저도 스크린샷이나 재현할 수 있는 방법을 공유해주시면 좀더 잘 확인할 수 있을 것 같네요!
2번 sitemap은 저도 정확한 시간은 기억이 나지 않습니다만 꽤 시간이 걸렸던 것으로 기억하는데요😭 
조금만 더 기다려보시길 추천드립니다!🙏

**Comment by zoomkoding** [comment]
@Shim8934님 말씀해주신 버그는 확인하여 수정했습니다!
위에 링크 되어있는 commit 내용을 확인하시면 수정 방법을 확인하실 수 있을 겁니다!
리포트 해주셔서 감사합니다!🙏

**Comment by Shim8934** [comment]
@zoomkoding 확인했습니다! 정상적으로 나옵니다 : ) 정말 감사드려요 : ) 설 연휴 잘 보내세요~!!
