### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by hyojinDev** [zoomkoding/zoomkoding-gatsby-blog#58]
관련 이슈 올라온 것 참고해서 제안해주신 방법들도 진행해보았는데 저는 아래와 같은 에러가 해결이 되지 않고있습니다ㅜㅜ..
이전에 한번 배포했었다가 문제가 생겨 레포지토리를 삭제 후, 지금 다시 블로그를 생성하려고 하니까 이런 에러들이 나오고 있어요!

제가 어떤 문제점을 파악하지 못하고있는걸까요..?

![스크린샷 2022-02-18 오후 11 38 34](https://user-images.githubusercontent.com/60868756/154704012-4be42dd1-d475-4322-8265-c3681bfbc401.png)

**Comment by zoomkoding** [comment]
@hyojinDev님 안녕하세요! 위 스크린샷만 봐서는 설치가 완료된 상태로 보입니다!
53 vulnerabilities라고 보이는 부분은 사용하는 라이브러리 간에 발생할 수 있는 이슈에 대한 warning인데요..!
이 부분은 gatsby가 버전 업 되면서 gatsby plugin들에서 생긴 warning들로,
현재 템플릿을 사용하시는데 있어서는 이슈가 없는 것으로 확인하고 있습니다!
npm start를 진행하시면 동작하는 것을 확인하실 수 있을 것 같습니다!🙏
