### ISSUE TITLE
Relative path for images in meta data

### ISSUE THREAD

**Issue by zoomKoding** [zoomKoding/zoomkoding-gatsby-blog#6]
projects의 이미지는 상대경로를 통해 등록이 안됨

**Comment by zoomKoding** [comment]
gatsby-meta-config에서 이미지 주소를 넣으실 때는
1. 이미지를 root에 있는 assets 폴더에 넣으시고 
2. 아래 같이 바로 파일명을 넣으시면 됩니다!

```
thumbnailUrl: 'timetable.png',
```

**Comment by C-Designer** [comment]
<img width="1067" alt="스크린샷 2021-07-07 오전 8 20 43" src="https://user-images.githubusercontent.com/69777689/124677837-3c510680-defc-11eb-80da-f8ae25802963.png">
왜 안되는지 잘 모르겠습니다..ㅠ
