### ISSUE TITLE
blog repository 생성시 경고 문구 & npm install ERROR

### ISSUE THREAD

**Issue by limeorange** [zoomkoding/zoomkoding-gatsby-blog#65]
안녕하세요 줌코딩님!
우선 깔끔하고 직관적이고 멋진 테마 만들어주시고 설명까지 친절하게 포스팅 해주셔서 감사합니다!!
줌코딩님의 테마가 맘에 쏙 들어 큰 맘 먹고 첫 깃헙 블로그 도전하려고 하는데 난관이 많네요..

우선 줌코딩님 링크를 넣고 repository를 만들면
`gh-pages had recent pushes 14 minutes ago`
`docs had recent pushes 14 minutes ago`
라는 문구가 뜨는데 그 옆의 Compare & pull request를 눌러도 딱히 변경할만한 버튼이 뜨지 않습니다..
왜 이런 문구가 뜨는 걸까요..?ㅠㅠ

그리고 node ver 14이상으로 설정하고 npm install 하니까 이런 에러가 뜹니다..

<img width="642" alt="스크린샷 2022-06-24 오후 2 48 03" src="https://user-images.githubusercontent.com/78308684/175470807-a9d90db0-5631-49e9-9e78-c49ecb147da1.png">

git 다루는 법을 잘 몰라서 어디서부터 잘못된건지 파악하기가 힘드네요ㅠㅠ
혹시 해결방법을 아신다면 알려주시면 감사하겠습니다!

**Comment by Guest-01** [comment]
> 우선 줌코딩님 링크를 넣고 repository를 만들면
gh-pages had recent pushes 14 minutes ago
docs had recent pushes 14 minutes ago
라는 문구가 뜨는데 그 옆의 Compare & pull request를 눌러도 딱히 변경할만한 버튼이 뜨지 않습니다..
왜 이런 문구가 뜨는 걸까요..?ㅠㅠ

우선 이 문구들은 무시하시면 됩니다. repository를 import해 왔기 때문에 발생하는 문구이고 정상입니다.

> 그리고 node ver 14이상으로 설정하고 npm install 하니까 이런 에러가 뜹니다..

에러 하단의 설명처럼 `--force` 또는 `--legacy-peer-deps` 옵션을 넣어서 다시 해보시기 바랍니다.
즉, `npm install --force` 혹은 `npm install --legacy-peer-deps` 이렇게요.

**Comment by zoomkoding** [comment]
디펜던시 이슈를 해소했는데 관련 이슈로 보이네요. package.json, package-lock.json을 복사해서 다시 테스트 부탁드립니다!
