### ISSUE TITLE
viewCount 안보이는 증상

### ISSUE THREAD

**Issue by HA-SEUNG-JEONG** [zoomkoding/zoomkoding-gatsby-blog#75]
몇달전부터 글에서 viewCount가 안보이는 현상이 있는데
줌코딩님 코드랑 비교해봐도 다른게 없는 거 같은데 뭐가 문제일까요..?

<img width="299" alt="image" src="https://user-images.githubusercontent.com/88266129/216628521-47d608ad-f3d1-493f-91dd-92f99c20d768.png">

제 코드에서 blog-template.js에서 data를 찍어보니 data가 자체가 null이라 안보이는 거 같은데 뭐가 문제인지 모르겠네요 ㅠㅠ
<img width="583" alt="image" src="https://user-images.githubusercontent.com/88266129/216628865-0fb300ee-33f7-4023-b09e-5a97727ba528.png">

https://github.com/HA-SEUNG-JEONG/HA-SEUNG-JEONG.github.io
 
제 레포지토리입니다!

**Comment by zoomkoding** [comment]
viewcount에서 사용하던 라이브러리가 deprecated되어 기능 제거했습니다.😂
